### ISSUE TITLE
[BUG] Pokemon Arceus is not being recognized

### ISSUE THREAD

**Issue by Terkyz** [ZachAR3/YuzuToolbox#57]
**Describe the bug**
I can't show it in the screenshot but Pokemon Arceus among other games is not being recognized and I can't download any mod

**To Reproduce**

1. Add mod path to PineApple
2. Enter the mods section
3. Search Pokemon Arceus
. 
**Expected behavior**
Pokemon Arceus showing correctly in the list of games to install mods.

**Screenshots**
Pokemon Arceus [not showing](https://i.imgur.com/QR6cMpO.png) on mod list.

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Version 3709

**Additional context**
I'm also getting an API error saying it's been used too many times, I don't know if it's related

**Comment by ZachAR3** [comment]
> **Describe the bug** I can't show it in the screenshot but Pokemon Arceus among other games is not being recognized and I can't download any mod
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add mod path to PineApple
> 2. Enter the mods section
> 3. Search Pokemon Arceus
>    .
>    **Expected behavior**
>    Pokemon Arceus showing correctly in the list of games to install mods.
> 
> **Screenshots** Pokemon Arceus [not showing](https://i.imgur.com/QR6cMpO.png) on mod list.
> 
> **Desktop (please complete the following information):**
> 
> * OS: KDE Neon
> * Version 3709
> 
> **Additional context** I'm also getting an API error saying it's been used too many times, I don't know if it's related

The API error is something I can't fix sadly, as github has a limit of 60 requests per hour for anonymous users. You can insert your github token in the settings panel to fix this or wait an hour for your requests to reset. The pokemon arceus issue I do know about, the key is just straight up missing from the title key site, however, it is the only title key site I can find that is actively maintained so I am still looking for solutions.

**Comment by ZachAR3** [comment]
Now in a thread #59 and fixed by manual adding it to the titles list in the latest commit.
