### ISSUE TITLE
[REFACTOR] Broken variables

### ISSUE THREAD

**Issue by matmat37000** [ZachAR3/YuzuToolbox#70]
**Is your refactor request related to a problem? Please describe.**
In `Installer.cs` in the function `GetLatestVersion()` (l.326) and `UnpackAndSetPermissions()` (l.351) the following variables does not exist in current context ([CS0103](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103?f1url=?appId%3Droslyn%26k%3Dk(CS0103))):

- `_repoOwner` (334,53)
- `_repoName` (334,65)
- `_pineappleLatestUrl` (343,65)
- `_windowsFolderName` (367,81)

**Describe the solution you'd like**
Assign a value to them so it stop the program to not being compile or delete them

> **Additional context**
> *Add any other context or screenshots about the feature request here.*

**Comment by matmat37000** [comment]
View #71

**Comment by matmat37000** [comment]
View solution in #71

**Comment by ZachAR3** [comment]
FYI, this is largely irrelevant, as almost all of these variables have been deprecated and I am using more generic ones now to accommodate supporting multiple sources.
